89 navigation styling - Micheale Andemariam
PakizeBozkurt/hugsforbugs pull request #109
Opened 2023-03-17 16:53 UTC by micheale2021

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Write a summary of your change. Explain why you have made it.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #89

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-03-17 16:57 UTC, micheale2021 commented
I have added a hover effect to NavLinks but have not added underline functionality for the current page. I have the code/logic but it's taking some time to implement it with the existing code. If we have enough time I will create a ticket and implement that.
Thank you.

2023-03-17 19:00 UTC, RainbowGiantSquid requested changes
A couple of comments to address, but other than that looking great!

2023-03-17 19:00 UTC, RainbowGiantSquid commented on client/src/components/NavBar.js
> +                 <Nav.Link className="nav-link active" href="/all-users">
good idea of using the class, however active class should be applied dynamically based on current page displayed. so if user is on 'all users' the that menu item has the active class

2023-03-17 19:00 UTC, RainbowGiantSquid commented on client/src/components/main.css
> +
navigation link text is not align in the centre, but the hover works nice, should be a slightly different colour though.

<img width="141" alt="image" src="https://user-images.githubusercontent.com/38047481/225994215-ec847960-7eb2-424f-ae2c-23f80ee830b9.png">

2023-03-17 19:00 UTC, RainbowGiantSquid commented on client/src/components/main.css
> +
Also the dropdown button with the initals needs styling to be round or at least the chevron displayed on the same line height
<img width="437" alt="image" src="https://user-images.githubusercontent.com/38047481/225994649-aea64885-8e67-4946-8e39-9b273d99e2a5.png">

2023-03-20 09:29 UTC, micheale2021 commented on client/src/components/NavBar.js
> +                 <Nav.Link className="nav-link active" href="/all-users">
className active removed, for now, I will be working on a different ticket.

2023-03-20 09:55 UTC, micheale2021 commented on client/src/components/main.css
> +
Chevron is displayed on the same line, the hover effect is removed for now.

2023-03-20 09:57 UTC, micheale2021 commented
Let's merge this, for now, it has a nav bar background colour light. I will work on a separate ticket for the rest.

2023-03-20 19:31 UTC, RainbowGiantSquid approved these changes
Looking good - I've resolved conflicts and removed the 'active' - perhaps the adding 'active' is a candidate for the further implementation - this class should be added dynamically when the current page path equals the link. so if you are on /all-users, the 'active' class is added to the 'All Users' link.
Anyway, all good.

2023-03-20 19:31 UTC, merged