#86-footer-styles-and-responsivness- Pakize-Bozkurt
PakizeBozkurt/hugsforbugs pull request #93
Opened 2023-03-14 10:06 UTC by PakizeBozkurt

## Naming Rules

#86-footer-styles-and-responsivness- Pakize-Bozkurt

## Description

Implemented responsive footer component

## Related to

Fixes #86

## Checklist:

- [ Y ] My code follows the style guidelines of this project
- [ Y ] I have carefully reviewed my own code
- [ Y ] I have commented my code
- [ Y ] I have updated any documentation

2023-03-14 11:25 UTC, RainbowGiantSquid requested changes
Looks good, I think some files removed here by mistake

2023-03-14 11:25 UTC, RainbowGiantSquid commented on server/emailsending.js
> -const express = require("express");
this PR is removing emailsending.js - seems to me quite important. This is just an footer styling PR so shouldn't be commiting any other changes.

2023-03-14 12:03 UTC, PakizeBozkurt commented on server/emailsending.js
> -const express = require("express");
I was trying to modify back-end side.
 It was happened by mistake.
 I added it again.
 😄

2023-03-16 16:38 UTC, RainbowGiantSquid approved these changes

2023-03-16 16:38 UTC, merged